import { Toaster } from '@/components/ui/sonner';
import { ptBR } from '@clerk/localizations';
import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';

const poppins = Poppins({
	variable: '--font-poppins',
	subsets: ['latin'],
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider localization={ptBR}>
			<html lang='pt-BR' suppressHydrationWarning>
				<body className={`${poppins.className} antialiased light`}>
					<Toaster
						closeButton={false}
						position='bottom-center'
						richColors
						theme='light'
					/>
					{children}
				</body>
			</html>
		</ClerkProvider>
	);
}
